#! /usr/bin/env python

import unittest, sys, types

class TestLoader(unittest.TestLoader):
    def loadTestsFromModule(self, module):
        '''Override so we can use suites already defined in the modules
	'''
        tests = []
        if hasattr(module, 'suite'):
            return module.suite()
        for name in dir(module):
            obj = getattr(module, name)
            if type(obj) == types.ClassType and issubclass(obj, TestCase):
                tests.append(self.loadTestsFromTestCase(obj))
        return self.suiteClass(tests)

if __name__ == '__main__':
    unittest.TestProgram(module=None, argv=sys.argv, testLoader=TestLoader())


# vim: set filetype=python ts=4 sw=4 et si
